# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Code/CPUshizhan/cdp_ede_local-master/cdp_ede_local-master/mycpu_env/soc_verify/soc_bram/run_vivado/constraints/soc_lite_top.xdc

# IP: D:/Code/CPUshizhan/cdp_ede_local-master/cdp_ede_local-master/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/data_ram/data_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet
